"use client";
import React, { useState } from "react";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@components/Navbar";
import { LightTheme } from "@/utils/CustomTheme";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import Footer from "@components/Footer";
import NextTopLoader from "nextjs-toploader";
import { lightColor, darkColor } from "@/utils/CustomTheme/color";
import { Provider } from "react-redux";
import { store } from "../../../store";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { SessionProvider } from "next-auth/react";
import { usePathname } from "next/navigation";
import { EdgeStoreProvider } from "@components/EdgeStore";
import { useSelector } from "react-redux";
import ThemeState from "@components/ThemeState";
import WhatsappIcon from "@components/WhatsappIcon";
import { Box, Typography } from "@mui/material";
import BlackBanner from "@components/BlackBanner";
import Head from "next/head";
import AuthProvider from "../AuthProvider";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ["latin"] });

// Create a custom theme with a 10px base font size

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const [themeState, setThemeState] = useState("");
  const themeValue = (state: any) => {
    setThemeState(state);
    return state;
  };
  return (
    <>
      {/* <SessionProvider> */}
          <ThemeState themeValue={themeValue} />
          {/* <ThemeProvider theme={LightTheme}> */}
            
            <EdgeStoreProvider>
              {/* application content */}
              {/* <body className={inter.className}> */}
                {/* <Box
                  sx={{
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center",
                    width: "100vw",
                    height: "100vh",
                  }}
                >
                  <Typography sx={{ textAlign: "center" }}>
                    Server Error 500
                  </Typography>
                </Box> */}
                {/* <NextTopLoader
                  color={lightColor.theme.primary}
                  initialPosition={0.08}
                  crawlSpeed={200}
                  height={3}
                  crawl={true}
                  easing="ease"
                  speed={200}
                  shadow={`0 0 10px ${
                    themeState === "light"
                      ? lightColor.theme.primary
                      : darkColor.theme.primary
                  },0 0 5px ${lightColor.theme.primary}`}
                /> */}
                {/* <AuthProvider> */}
                {pathname === "/" ? <BlackBanner /> : ""}
                  <Navbar/>
                {children}
                {/* <WhatsappIcon /> */}
                {pathname === "/bulk-query" ? "" : <Footer />}
                {/* </AuthProvider> */}
                <ToastContainer
                  position="bottom-left"
                  autoClose={3000}
                  hideProgressBar
                  newestOnTop={false}
                  closeOnClick
                  rtl={false}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="light"
                />
              {/* </body> */}
            </EdgeStoreProvider>
          {/* </ThemeProvider> */}
      {/* </SessionProvider> */}
    </>
  );
}
